### PR TITLE
Adding compatibility with LLC grid (new branch)

### PR DESCRIPTION
**Pull request by Mikejmnez**
This is a new PR from a new branch, which will add compatibility to manipulate and process data defined on LLC grid (with faces). It does so by removing faces as a dimension and can create regional cutouts of the data while preserving the original grid.

### CODE REVIEW

**Comment by malmans2** [comment]
The test data are currently stored in my OneDrive, and downloaded into `oceanspy/tests/Data/` by this [script](https://github.com/hainegroup/oceanspy/blob/master/oceanspy/tests/conftest.py). If you need to add test data, you could create a new separate repository and add it to the script. I'm also happy if you want to use a single repository that includes the data I currently own (i.e., add the old data to the new repository).

**Comment by asiddi24** [comment]
Will you be having access to your OneDrive in the long term ?

**Comment by Mikejmnez** [comment]
I think it would make sense all the data in the same place, and @asiddi24 brings a good point about long-term storage.

**Comment by malmans2** [comment]
It should be fine for at least one year, but I agree that it would be better to find a better solution. We don't even have to stick with JHU OneDrive!

**Comment by asiddi24** [comment]
The `get_started` test data is just a few hundred MB. I'm guessing the LLC test data would not be too big as well, if it's trimmed down to bare minimum. SciServer seems like an obvious choice, then.

**Comment by malmans2** [comment]
The problem is that we run tests using Travis, not on SciServer. Currently, you can't download data using just a link from SciServer. We need a repository in the cloud. Anything with public access would work.

**Comment by asiddi24** [comment]
That would mean something like AWS or Google Cloud Storage ? Like the way Pangeo data is stored ?

**Comment by malmans2** [comment]
That would work, or even a hainegroup Dropbox, GitHub if it's small enough (like [xarray](https://github.com/pydata/xarray-data)), whatever is convenient. I used OneDrive, but I didn't really think about what's the best option (we actually used JHU box, then we migrated to OneDrive #127).

**Comment by asiddi24** [comment]
Ah ! Sweet

**Comment by Mikejmnez** [comment]
All these options (besides JHU onedrive) sound good to me. As to llc-data, we just need a couple of variables, a couple of snapshots, which requires very minimum storage -- I have almost all vars in my local machine, for 1 snapshot. It is much much less than 1GB and we need less than that for the test

**Review by asiddi24 — COMMENTED** [review]
Would you need to make changes to the catalogue entry too ? Like you mentioned before, it'll be convenient  if you create an issue regarding this.

**Comment by Mikejmnez** [comment]
> Would you need to make changes to the catalogue entry too ? Like you mentioned before, it'll be convenient if you create an issue regarding this.

I did the necessary changes on the catalog of my branch (the one from this PR), for both LLC90 and LLC4320 so it should work...

**Comment by asiddi24** [comment]
Thanks for making the changes we discussed @Mikejmnez . Only concern is that tests seem to be failing.

**Comment by Mikejmnez** [comment]
@asiddi24 of course! I am going to go through these in the next day or so.

**Comment by asiddi24** [comment]
Great ! we can merge to master then.

**Comment by Mikejmnez** [comment]
@asiddi24 , yes, once I am done with the tests (no failed test...)

**Comment by Mikejmnez** [comment]
Looks like at I am the same failed test as in #157 : a missing warning while running ```test_time_resampling``` in ```test_subsample.py```. I'll wait to see what @malmans2 is able to see/resolve, as he has more experience with what these warnings should be doing

**Comment by malmans2** [comment]
@Mikejmnez your current branch is a bit outdated (just minor things to keep up with the dependencies). Do you also see the `Update branch` button at the bottom of this page? This will integrate you changes with the master branch!

**Review by ThomasHaine — DISMISSED** [review]
Are we all set to merge?  The failing tests are benign?

**Comment by asiddi24** [comment]
Yes

**Comment by malmans2** [comment]
The failing test is an easy fix, I should have time to do it tomorrow. 
@Mikejmnez and @asiddi24 are you planning to add tests before merging? It looks like currently llc_rearrange is not tested:

codecov

BTW, if you are working on tests you can create a html report. I used it a lot when I was writing the tests. Here is the command:
```sh
py.test oceanspy -v --cov=oceanspy --cov-config .coveragerc --cov-report term-missing --cov-report=html
```
It creates a directory named `htmlcov` with all the reports.

**Comment by Mikejmnez** [comment]
@malmans2 Yes, I should be done writing tests by tomorrow. This brings again the issue of where to store and access the data (a couple of snapshots of llc90 data would do)...

**Comment by malmans2** [comment]
@pep8speaks suggest diff

**Comment by malmans2** [comment]
pep8speaks was not hooked. Should be fixed now, but I don't know if it will work on this PR or from next.

@pep8speaks suggest diff

**Comment by malmans2** [comment]
All tests passing now!

**Comment by malmans2** [comment]
I've created a new repo with test data (so we are sure we don't break the master tests).
[Here is the new link.](https://github.com/hainegroup/oceanspy/pull/148/commits/69ba69970b5ec7d30893c65dc46058503a4e6980)
The new repo contains old test files + new ECCO test files.
As before, the files are downloaded and uncompressed into the tests directory. 
Here are the new files:
```
oceanspy/tests/Data/ECCO_v4/GRID:
ECCO-GRID.nc

oceanspy/tests/Data/ECCO_v4/THETA:
THETA_1992_01.nc

oceanspy/tests/Data/ECCO_v4/UVEL:
UVEL_1992_01.nc

oceanspy/tests/Data/ECCO_v4/VVEL:
VVEL_1992_01.nc
```

**Comment by Mikejmnez** [comment]
I am Still working on it, just working by parts. Will let you guys know when its done

**Comment by Mikejmnez** [comment]
Looks like PR is ready. The relative coverage is at 84% (down from 95%). I am going to continue working today on increasing the coverage (mostly on ```llc_rearrange.py```). Then, tomorrow should be ready for merging (closer to ~95% coverage than right now).

**Comment by asiddi24** [comment]
This is awesome !

**Comment by Mikejmnez** [comment]
I think I am done with tests. Looks like coverage is 95.5%, down from 98%...

**Review by ThomasHaine — COMMENTED** [review]
Great work Miguel!  @malmans2 I'll let you make final approval and merge.

**Comment by Mikejmnez** [comment]
@malmans2 Sure, I have already put enough data on sciserver, that should be ready to test. I think @asiddi24  also added some more. <s>This reminds me I will update </s> the intake catalog on the PR <s>to allow</s> should allow to read / create the Ospy object from llc90 data. A bit slow, but should be ready to go... Just do:

```python
od = ospy.open_oceandataset.from_catalog('LLC90', url)
```

where
```python
url = ("https://raw.githubusercontent.com/Mikejmnez/oceanspy/llc4320/sciserver_catalogs/catalog_xarray.yaml")
```


> A nice notebook to show in the documentation is the only thing we are missing. But it can also be added later through a separate PR... up to you!

I agree, the documentation needs to be updated, and will work on an aspect of this (Ali will work on budget calculations), but lets leave it to another PR.

**Comment by malmans2** [comment]
I'll test an up2date environment so we can upgrade the SciServer image as well. Does anyone need more packages on SciServer?
Here is the current list: https://github.com/hainegroup/oceanspy/blob/master/sciserver_catalogs/environment.yml

**Comment by asiddi24** [comment]
I think we're set with the packages for now.

**Comment by malmans2** [comment]
All good! @Mikejmnez one final thing.
The datasets in  [datasets_list.yaml](https://github.com/Mikejmnez/oceanspy/blob/new_llc4320/sciserver_catalogs/datasets_list.yaml) should match the datasets in the intake catalog. I think a few of them are actually commented in the catalog. I'd clean up comments in the catalog, and update the dataset list accordingly.

If there are datasets that you'd like to have on SciServer but you don't want to expose in the [documentation](https://oceanspy.readthedocs.io/en/latest/datasets.html), do the same we are doing for Renske's Arctic configuration:
https://github.com/Mikejmnez/oceanspy/blob/531f5c70e6708a13e8171952054fe64b429efe09/docs/conf.py#L238-L240

**Comment by Mikejmnez** [comment]
> All good! @Mikejmnez one final thing.
> The datasets in [datasets_list.yaml](https://github.com/Mikejmnez/oceanspy/blob/new_llc4320/sciserver_catalogs/datasets_list.yaml) should match the datasets in the intake catalog. I think a few of them are actually commented in the catalog. I'd clean up comments in the catalog, and update the dataset list accordingly.
> 
> If there are datasets that you'd like to have on SciServer but you don't want to expose in the [documentation](https://oceanspy.readthedocs.io/en/latest/datasets.html), do the same we are doing for Renske's Arctic configuration:
> https://github.com/Mikejmnez/oceanspy/blob/531f5c70e6708a13e8171952054fe64b429efe09/docs/conf.py#L238-L240

Sounds good, and like a quick fix. Because LLC4320 data and POP/HYCOM are not ready to be publicly available yet, I will do the same as Renske did for the Arctic configuration.

@asiddi24 Is there any other variable that is not in the catalog that you think we should make available? (UVELMASS, VVELMASS?, mixed layer depth?, etc)

**Review by malmans2 — APPROVED** [review]

**Comment by malmans2** [comment]
@Mikejmnez can you please also update the [History](https://github.com/Mikejmnez/oceanspy/blob/new_llc4320/HISTORY.rst) section? 
Add on top an entry **v0.2.0 (unreleased)**.

**Comment by Mikejmnez** [comment]
I am getting annoyed at the code coverage report hahaha.

**Comment by malmans2** [comment]
I've updated the ci workflow. The whole coverage must be 90% in order to merge (llc_rearrange is around 86%). If you think it's good, go for it and merge! I'll bump to 0.2 when you merge.

**Review by malmans2 — CHANGES_REQUESTED** [review]
Could you please add a sentence in HISTORY describing the new functionalities? And add your name as well!

**Review by asiddi24 — APPROVED** [review]

**Comment by Mikejmnez** [comment]
> I've updated the ci workflow. The whole coverage must be 90% in order to merge (llc_rearrange is around 86%). If you think it's good, go for it and merge! I'll bump to 0.2 when you merge.

I might work later on some aspects of it (tests) and increase coverage on a different PR (say the one with improved documentation). For now, I am happy with the current state (also, its been too long!).

**Review by asiddi24 — APPROVED** [review]

**Review by asiddi24 — APPROVED** [review]

**Comment by asiddi24** [comment]
Request to @malmans2 changes is done then. Can you approve changes and merge ?

**Review by malmans2 — APPROVED** [review]

**Comment by malmans2** [comment]
¡¡¡¡¡ LET'S GOOOO !!!!!

**Pull request merged**
