### PR TITLE
llc rearray update

### PR DESCRIPTION
**Pull request by Mikejmnez**
This is an update to `llc_rearrange.py`. It now uses exclusively xarray to manipulate datasets and remove faces (all or a subset) as a dimension (before bit of xarray and numpy, which was slow).

Some more changes will come in the next couple of weeks. But this is usable now.

Could use more testing. I will add more in the follow up PR.

### CODE REVIEW

**Comment by Mikejmnez** [comment]
don't understand why these test fail. All these passed within the ```oceanspy_test``` environment...

**Comment by malmans2** [comment]
I think the test failure is unrelated to this PR. I didn't have the time to look into it, but tests started failing last week in the master branch as well. https://github.com/hainegroup/oceanspy/actions/runs/1806606996

**Review by ThomasHaine — COMMENTED** [review]
Looks good to me...apart from the failing tests. Can we merge now or do the failing tests need to be fixed first?

**Comment by Mikejmnez** [comment]
> 

I think keeping track of why these test are failing is important, but there is a way to go through with this PR. The issue seems to be two failing tests associated ```test_anim_Hsection``` (lines 85-101 in ```test_animate.py```).  One thing we could try is to comment those tests and go through the PR and fix this issue later... It is going to decrease coverage but it will only be temporal.

**Comment by ThomasHaine** [comment]
@malmans2 What do you prefer?  Fix the failing tests first then merge or vice versa?

**Comment by ThomasHaine** [comment]
Huh, now the tests pass...

**Comment by Mikejmnez** [comment]
> Huh, now the tests pass...

@ThomasHaine the issue is still there, I commented the two failing tests in ```test_animate.py```. I don't know what the issue is yet, but I guess I am suggesting that if we are OK with moving forward with this PR before fixing the issue, for now, commenting two tests allows this PR to pass. I describe what the failing tests are in PR #212

**Comment by ThomasHaine** [comment]
> > Huh, now the tests pass...
> 
> @ThomasHaine the issue is still there, I commented the two failing tests in `test_animate.py`. I don't know what the issue is yet, but I guess I am suggesting that if we are OK with moving forward with this PR before fixing the issue, for now, commenting two tests allows this PR to pass. I describe what the failing tests are in PR #212

Understood. I'm happy to merge.

**Comment by Mikejmnez** [comment]
Lets hear Mattia @malmans2 's opinion. This is clearly only a temporary solution. I just don't really have time to figure what the issue with the update in PR #212 is.

**Comment by malmans2** [comment]
Hi!
I'm quite busy in the next couple of weeks and I don't have much time to look at it. Feel free to merge when you're ready (maybe Ali could take a quick look and approve?).

Regarding tests, don't worry about those, they are not related to this PR. But I don't think commenting out the tests is the best way to go. I'd merge this PR even if tests are failing, then we'll address those issues in a separate PR.

Are you able to merge even if tests are failing? Let me know if you can't and I'll change your permissions, I think you are "maintainer" right now.

**Comment by Mikejmnez** [comment]
Got it. I didn't know you could approve with failing tests. I un-commented the failing tests (unrelated with this PR) and will wait for @asiddi24 to take a look at this PR.

 I don't think I can merge when tests are failing..

**Comment by malmans2** [comment]
You are admin now... can you merge? You should be able to see this:
image

**Comment by Mikejmnez** [comment]
> You are admin now... can you merge? You should be able to see this: image

Yes , I can now. wow, with great power comes great responsibility...

**Pull request merged**
