### PR TITLE
Update binder

### PR DESCRIPTION
**Pull request by malmans2**

### CODE REVIEW

**Comment by malmans2** [comment]
I've updated the binder repo. You can see a preview here: https://mybinder.org/v2/gh/hainegroup/oceanspy/binder?filepath=binder

**Review by ThomasHaine — COMMENTED** [review]
Looks great!  I ran the demo presentation and tutorial notebook with no issues (apart from a few warnings). I couldn't find the demo presentation in readthedocs after a brief exploration. It's worth putting it in (e.g.) Quick Start.

**Comment by malmans2** [comment]
Good idea! I've added the link in the home page and at the bottom of quick start. What do you think?

**Comment by ThomasHaine** [comment]
I don't see the presentation links.

**Comment by malmans2** [comment]
Are you looking at the readthedocs website?
If yes, it won't show the additions until we merge (you could compile locally following [this](https://oceanspy.readthedocs.io/en/latest/contributing.html#contributing-to-the-documentation)).
If you look at the readme of this PR (https://github.com/hainegroup/oceanspy/tree/bind), there is this link: www.bndr.it/nakt7

The binder link it's not showing the Live_Demo.ipynb yet, it will once we merge. (Once we merge  www.bndr.it/nakt7 will display this https://mybinder.org/v2/gh/hainegroup/oceanspy/binder?filepath=binder)

**Comment by malmans2** [comment]
Also, I'm fixing the tests in a separate PR!

**Comment by malmans2** [comment]
I pasted the wrong link before. Here is the correct link of this branch: https://github.com/hainegroup/oceanspy/tree/binder

**Comment by ThomasHaine** [comment]
OK, understood. I was looking at the readthedocs website. I'm happy to merge now and see the updated docs when they're live.

**Comment by ThomasHaine** [comment]
> I pasted the wrong link before. Here is the correct link of this branch: https://github.com/hainegroup/oceanspy/tree/binder

Looks good!

**Comment by malmans2** [comment]
OK! If #163 passes all tests, I'll merge that one first, then this.

**Comment by malmans2** [comment]
All set!

**Comment by asiddi24** [comment]
Is it strange that when I run the binder it always runs on a jupyter notebook but not on jupyter lab ? Or is that just default in my system ?

**Comment by malmans2** [comment]
I don't remember if that was intentional, but I'm pretty sure there is a way to set it. (Maybe here https://github.com/hainegroup/oceanspy/blob/master/binder/postBuild or something similar?).

I'm thinking that classic jupyter might be easier for people that are not familiar with it, but feel free to explore the lab option if you think it's better!

**Pull request merged**
