### PR TITLE
xhistogram added to Statistics tutorial

### PR DESCRIPTION
**Pull request by ThomasHaine**
The volumetric census over TS classes at the end of the Statistics tutorial has been added using xhistogram.

### CODE REVIEW

**Comment by ThomasHaine** [comment]
@malmans2 the travis-ci check failed for python 3.6. Is that because of the onedrive instability (see the log)?  How do I run the travis-ci check manually?

**Comment by malmans2** [comment]
Yes, I'm pretty sure that's the reason. 
Try this: 
* Click on `Details` near `continuous-integration/travis-ci/pr` (below this message).
* Then click on the build that is failing. 
* Then click on `Restart job`. It should be on the top-right. 
If you don't see it, then I might have to change some permission.
But I think you should be able to do it because you are already in the [CODEOWNERS](https://github.com/malmans2/oceanspy/blob/master/CODEOWNERS) list. Make sure you are logged into github before clicking on `Details`.

Let's wait a couple of weeks. If this OneDrive problem persists we should switch to another cloud storage.

**Comment by malmans2** [comment]
Actually, maybe you have to manually log into Travis using your Github account.

**Comment by malmans2** [comment]
Although `xhistogram` is not a dependency, I've added it in the SciServer environment. It will be installed in the next Oceanography image.

**Review by asiddi24 — COMMENTED** [review]
Good to go. I made a new container for OceanSpy in SciServer and after having installed xhistogram from conda-forge, the notebook works fine.

**Review by asiddi24 — APPROVED** [review]

**Pull request merged**
