### PR TITLE
upgrade actions and avoid fsspec 0.9.0

### PR DESCRIPTION
**Pull request by malmans2**
Minor cleanup.
Remove old useless files and switch off codecov failures.

### CODE REVIEW

**Comment by malmans2** [comment]
There are issues with the catalog parser. I'm getting it in other repos as well, so I don't think it's an OceanSpy bug. Non sure yet where it's coming from.

**Comment by ThomasHaine** [comment]
So we just wait for bugs to resolve?  Otherwise, it looks good to me. I can approve now if you prefer.

**Comment by malmans2** [comment]
OK. The issue is fsspec 0.9.0. The master branch is already fixed, so we can just force `fsspec!=0.9.0`.
Feel free to merge if all tests pass!

**Comment by malmans2** [comment]
OK. We can now merge this.

**Pull request merged**
