### PR TITLE
Adding compability with LLC gridded data (+ ECCOdata)

### PR DESCRIPTION
**Pull request by Mikejmnez**
This is just to get the ball rolling. I still need to work on the transformation that creates a new dataset getting rid of faces, and thus recovering all the functionality of ``oceanspy`` and ``xgcm`` (grid diff and interpolation).

So far, the code as it is will create an ospy object ``od``, with the right attributes and a consistent grid topology/grid object. The location of zarr files is defined on the sciserver catalogs, so you can test it.

There are a couple of things to consider: 
1. Transform functions (not included here) are still under develop, but will most likely be merged with code on the ``xmitgcm``. Thus, they will only be called from the ``subsample.cutout`` function.
2. ``Zarr`` stores will (in the future) be opened with ``xarray.open_dataset``, which will affect also how these files are open through the intake catalog (``intake-xarray``). It remains to be seen if the ability to multiple zarr files (with ``parallel=True``) will be possible from ``intake-xarray``. So it is possible that we just add such behavior on oceanspy.

I haven't had the time to finish working with the transformation of the dataset. I am hoping to get it done soon! For now, we can check some of the changes I have made to the code (not many, despite the many commits, it was a lot of trial by error while learning the code and testing it on sciserver).

https://github.com/pydata/xarray/pull/4003#pullrequestreview-402343711

### CODE REVIEW

**Comment by malmans2** [comment]
@Mikejmnez there are a bunch of conflicts, I think mainly because of formatting. Have you tried something like this (see the note)? http://xarray.pydata.org/en/v0.14.0/contributing.html#code-formatting

**Comment by Mikejmnez** [comment]
Hey @malmans2  I ran black and flake8 (which introduced some new formatting changes). I didn't ran isort. Are there particular ones I should be running?

**Comment by malmans2** [comment]
Yes, just black (and black-nb) + flake8 is what we are using. But I think you also need to rebase because you have been working on a old version of the code. Otherwise you'd have to manually solve all the conflicts.

**Comment by Mikejmnez** [comment]
This has all my code, which I have tested with ECCO data and some LLC4320 surface data. Most of the new code is on llc_rearrange.py merges faces and eliminate face as a dimension. That part of the code works in a particular way (I made a repository on my github so can be tested stand-alone). With it, now subsample.cutout can produce a new dataset without face as a dimension, in a way that incorporates the Arctic cap if required. Below an example of dataset (no face) that contains data from faces 2, 6 and 10 (rotated, non-rotated and the arctic cap).


LLC4320_SST_cutout_faces_2_6_10

**Comment by malmans2** [comment]
Nice! I'm going to take a look at this in the next few days. In the meantime, a couple of points we should keep in mind.

- [ ] Do we need to add tests? I noticed that this PR didn't get a coverage report. If anyone wants to investigate why, this is probably the starting point: https://codecov.io/gh/hainegroup/oceanspy/pull/146
- [ ] We should definitely add a specific notebook in the use cases section of the documentation.
- [ ] What about also adding some test data on SciServer? The filedb nodes are not public yet, so I'd say to start with some test data on the Oceanography volume.

Also, quick comment about the workflow. As we don't interact with each other very often, if anyone is checking out this PR please post feedback frequently here rather than just posting everything at the very end.

**Comment by Mikejmnez** [comment]
Yes, I agree about the tests and notebook. I can easily create a notebook with different examples displaying the possible uses of the transformation function with some example data, e.g. with both ECCO and/or LLC data (I can move some files to the Oceanography volume and reference them in the intake file). Also, I am reaching to both Chris and Ryan about vertical grid parameters for the LLC data (we only have the horizontal), but for visualization purposes, horizontal data will be enough...

**Comment by asiddi24** [comment]
One possibility is to just put the LLC90 data on the Sciserver which would be enough for demonstration purposes, but if possible LLC4320 can also be put up.

I'm checking out the PR for now too and I'll provide feedback more actively. Stay tuned !

**Comment by malmans2** [comment]
OK! This is what is available on the SciServer volume right now:
```
Filesystem            Size  Used Avail Use% Mounted on
sciserver-fs1:/srv/zpool04/oceanography
                       20T   19T  1.1T  95% /sciserver/oceanography
```
We might be able to move some dataset though if more space is needed!

**Comment by Mikejmnez** [comment]
Ok, I'll wait for Ali to move the ECCO dataset to the Oceanography volume, and see how much space there is available after for some snapshots of LLC surface data (just a couple of months-worth of surface data of temp and salinity is ~1Tb). Just maps of SST with LLC4320 would be good to have, since these look great! @asiddi24 if possible, try to put the data within the same folder, or at least each variable within a subfolder, so that it is easy to reference/point from an intake catalog (like all THETA files within ECCO_DATA/THETA or something like that...)

**Comment by Mikejmnez** [comment]
Hey guys. I copied most of the ECCO data into Sciserver on the Circulation volume. You can access the data through an intake catalog I created with the following url:

```python
url = "https://raw.githubusercontent.com/Mikejmnez/oceanspy/llc4320/sciserver_catalogs/catalog_xarray.yaml"
od = ospy.open_oceandataset.from_catalog('LLC90', url)
```

It is very slow even to load the data, mostly because this is a large dataset. I am commenting some intake entries on the catalog to read only a few variables (say U, V, T, Salt). It's still slow (compared to working on filedbnodes), but it works.  

When preparing to test the cutout function, you will need to reset the coords (I will change the code so you don't have to do this, but for now this works fine) as follows:

```python
ds = od._ds.reset_coords()
od._ds = ds
```

and need to define two variables: 

```python
# Transformation parameters
centered= 'Atlantic'  # default is Atlantic, 
transformation = 'arctic_crown'  # default is False
```
as arguments on the cutout function. To produce a cutout say, for example, on the NA I use:

```python
## Parameters
varList = ['T', 'Depth', 'U', 'V', 'Zed', 'Zed_p1','XC', 'YC','XG', 'YG', 'dxC', 'dyC', 'dxG', 'dyG']
YRange = [20, 80] # degrees latitude
XRange = [-90, 20] # longitude
add_Hbdr = False
mask_outside = True
ZRange = None
add_Vbdr = False
timeRange = '2017-01-16T12:00:00.000000000'
timeFreq= None
sampMethod = 'snapshot'
dropAxes = False
# Transformation parameters
centered= 'Atlantic'
transformation = 'arctic_crown'
cut_od = ospy.subsample.cutout(od,varList,YRange,XRange,add_Hbdr,mask_outside,
                               ZRange,add_Vbdr,timeRange,timeFreq,sampMethod,dropAxes, 
                               centered=centered, transformation=transformation)
```

**Comment by malmans2** [comment]
@Mikejmnez have you considered using the `consolidated` functionality to open the zarr object?
http://xarray.pydata.org/en/stable/generated/xarray.open_zarr.html
If it can be used, I think it would make the opening part very quick. You might have to recreate the zarr object though.

**Comment by malmans2** [comment]
I didn't check the details yet, but do you understand why the cutout hangs forever if I use `timeRange=None`?
I wasn't expecting it to take much longer than using just one time step, so probably the way I designed it originally is not ideal?

**Comment by Mikejmnez** [comment]
@malmans2 
> have you considered using the `consolidated` functionality to open the zarr object?
> http://xarray.pydata.org/en/stable/generated/xarray.open_zarr.html
> If it can be used, I think it would make the opening part very quick. You might have to recreate the zarr object though.

Interesting. I didn't think it was an option other than for storing zarr files... I actually have been using my own fork from xarray and intake that allows to read multiple zarr store in parallel and with that, I am able to open zarr files from the llc4320 data much much faster (i.e. I split the original zarr file into multiple new ones, much like netcdf files, each file with multiple variables and different time ranges). The ```xarray``` PR is almost done, and after that is done I will submit the intake PR . I think this will definitely have a greater impact on performance when opening multiple zarr files. I will also check the ```consolidate=True``` option from xarray... good suggestion


> I didn't check the details yet, but do you understand why the cutout hangs forever if I use timeRange=None?
> I wasn't expecting it to take much longer than using just one time step, so probably the way I designed it originally is not 
> ideal?

Good eye. I don't think I checked it before. I just went through the code and it looks like the original code has the statement
```python
if timeRange is None:  # line 220
    # code
```

but otherwise, doesn't have an extra option in case ```timeRange = None``` . I think we should have something like

 ```python
if timeRange is not None:
    # code here
else:
    # code chooses one snapshot, say the first one ds.isel(time=0) only.
```

Something that I did to improve performance, you probably noticed, is that I moved the ```time cutout``` and ```drop variables``` from the end of the ```cutout``` function, to the beginning. It made more sense to only perform horizontal and spatial cutouts to the relevant variables (defined in varLists) and relevant ```timeRange```. Before, the (spatial) cutout was applied to the whole (original) dataset, and so the last steps where to drop the timeRange not relevant, and then variables not in varList (in that order). It could be that when I moved these parts of the code (even though I tried to be careful, and so far it works), i left the ```else (to timeRange is None)``` parts somewhere behind; not likely but possible.... I think we could (should) raise a flag whenever any of the following is passed to the cutout function
```python
timeRange=None; xRange=None;  YRange=None; ZRange=None;

```
and maybe set a predefined value/option when any of these is passed. For example, 
```python
if ZRange is None:  
    # then keep all Z. This true also for X and Y. 
If timeRange is None: 
    # keep first snapshot only
```

**Comment by malmans2** [comment]
Mmmm... I think the horizontal cutout is supposed to operate on lat/lon only. It uses them to find the indexes of the cutout, then it uses isel and slice (e.g., something like `ds = ds.isel(x=slice(x0, x1))`).
The reason why the code finds the indexes first, then slices (rather than just applying a mask to the whole dataset, something like `ds.where(mask, drop=True)`) is that slicing should not depend on the variables in the dataset, because it only operates on the dimensions.

If it gets very slow, I think there are a couple of possibilities:
* something triggers the evaluation of the dataset (not lazy anymore)
* the mask applied to lat/lon to find the indexes of the cutout is actually applied do the whole dataset

Let me check if the master branch works the way it should with both rectilinear and rectilinear grids....
 
Edit: rectilinear and curvilinear

**Comment by malmans2** [comment]
I think something is broken in this PR for SciServer:
`od = ospy.open_oceandataset.from_catalog('EGshelfIIseas2km_ASR_full')`.
From the error it looks like OceanSpy is looking for a DataScope path (`/sciserver/oceanography/...`).
From a quick glance the url of the catalog in the code looks correct, any idea?

**Comment by malmans2** [comment]
> I think something is broken in this PR for SciServer:
> `od = ospy.open_oceandataset.from_catalog('EGshelfIIseas2km_ASR_full')`.
> From the error it looks like OceanSpy is looking for a DataScope path (`/sciserver/oceanography/...`).
> From a quick glance the url of the catalog in the code looks correct, any idea?

@Mikejmnez nevermind, my bad. I was using an old version of the PR I think. Sorry!

**Comment by Mikejmnez** [comment]
> > I think something is broken in this PR for SciServer:
> > `od = ospy.open_oceandataset.from_catalog('EGshelfIIseas2km_ASR_full')`.
> > From the error it looks like OceanSpy is looking for a DataScope path (`/sciserver/oceanography/...`).
> > From a quick glance the url of the catalog in the code looks correct, any idea?
> 
> @Mikejmnez nevermind, my bad. I was using an old version of the PR I think. Sorry!

Ok, I was just looking into this... Let me know if you have another issue with the PR. Something I did a long time ago (I already mentioned this to Ali) is that the branch that you clone from my fork is the llc4320 branch (which points to my catalog on github), but this PR is from the master branch... I was just looking into the master branch and I did find a commented urlpath on the catalog, just before you wrote this message. This is, on ```grd_EGshelfIIseas2km_ASR_full``` I have 

```python
urlpath: /sciserver/oceanography/exp_ASR/grid.nc
# urlpath: /home/idies/workspace/OceanCirculation/exp_ASR/grid.nc
```

I performed a lot of tests on datascope. I don't remember changing this but I can imagine I may have change this early on... Let me know if you get the same error...

**Comment by malmans2** [comment]
That was definitely the issue, so I guess I was using that one...

**Comment by Mikejmnez** [comment]
> That was definitely the issue, so I guess I was using that one...

Ok, I fixed the catalog entry to point to ```/idies/home/...``` on the master branch (also on the llc4320 branch), It should point to the right directory now...

**Comment by malmans2** [comment]
Let's remember this before we merge
- [ ] Check all catalog entries on SciServer (it's the only thing that is not automatically tested)

**Comment by Mikejmnez** [comment]
what I don't understand s why, after I install the master branch from my github, why opening a catalog points to my github catalog as opposed to Hainegroup? That is, if I install from my master branch, and do:
```python
 from oceanspy.open_oceandataset import _find_entries
cat, entries, url, intake_switch = _find_entries('EGshelfIIseas2km_ASR_full', None) 
entry=entries[0] # grid file
cat[entry].metadata
``` 
gives 
```catalog_dir: https://raw.githubusercontent.com/Mikejmnez/oceanspy/llc4320/sciserver_catalogs}```.

In the master branch, under ```find_entries``` I set the url to point to hainegroup... Its on the llc4320 branch that 
it points to my catalog... 

When installing the master branch I do

```pip install git+git://github.com/Mikejmnez/oceanspy@master```

**Comment by malmans2** [comment]
Do you see the command line instructions near the Merge pull request button (below this comment)?
I found the right info there:

Step 1: From your project repository, check out a new branch and test the changes.
```
git checkout -b Mikejmnez-master master
git pull https://github.com/Mikejmnez/oceanspy.git master
```
I've done that, then `pip install -e oceanspy/`

**Comment by Mikejmnez** [comment]
> Do you see the command line instructions near the Merge pull request button (below this comment)?
> I found the right info there:
> 
> Step 1: From your project repository, check out a new branch and test the changes.
> 
> ```
> git checkout -b Mikejmnez-master master
> git pull https://github.com/Mikejmnez/oceanspy.git master
> ```
> 
> I've done that, then `pip install -e oceanspy/`


Nice. I'll do that later. I've done it multiple times the other other way around (what I showed in previous comment) without an issue. Maybe there was and I just didn't noticed... Any way, the master branch (this PR) has always point to your original catalog entry, i.e. url=haingroup catalogs (find_entries)... So there shouldn't have been any problem there... cheers!

**Comment by malmans2** [comment]
[Here](https://nbviewer.jupyter.org/gist/malmans2/a691ad06837ebf31e8cd566a17bb2f3d) is a notebook that shows how time size and var list does not really matter for rectilinear and curvilinear grids. I ran the notebook on SciServer using this PR.

I'm not sure whether there's a workaround to get the same performance with LLC, and whether the slowdown is due to the grid, the file format, ...

**Comment by malmans2** [comment]
Closing in favor of #148 due to #147

**Pull request closed without merging**
