### PR TITLE
Add plots

### PR DESCRIPTION
**Pull request by malmans2**
* Add plot module: TS diagram
* Add projection attribute
* Address #54, #53,
* Implement aliases on missing functions

### CODE REVIEW

**Comment by malmans2** [comment]
Edit: I changed the syntax from `killAxes` to `dropAxes`:
* I added the option `dropAxes` in cutout. This option will remove the axes with just one point. For example, if you run `od.cutout(timeRange='2007-09-01')` it will return an oceandataset with 2 `time` points and 1 `time_midp` point. If you run `od.cutout(timeRange='2007-09-01', dropAxes=True)`, then `time` will be removed from the  grid object and it will return an oceandataset with 1 `time` and 1 `time_midp` dimension. It works on every dimension. So, let's say you only want 1 point in every Z dimension, then drop the Z axis.

* `dropAxes` can be set `True`, or you can specify the axis that you want to drop (e.g., `dropAxes=['time', 'Z']`). 

* Use `dropAxes` only if you are sure that you won't need the axis in the future. So, don't use it untill the very end of your script, use only use it for visualization purposes, like the example below.
* Now you can use cutout arguments directly in the plot function, and the title is more informative. 

Here are 2 examples that hopefully will make it more clear:

1. Don't drop the time axis, and get 2 time points even if `timeRange` only has 1 value:
```python
import oceanspy as ospy
%matplotlib inline
od = ospy.open_oceandataset.EGshelfIIseas2km_ASR()
od.TS_diagram(cutout_kwargs={'ZRange': 0, 'timeRange': '2007-09-01'}
```
notkilling

2. Drop the time axis, and get 1 time point only:
```python
import oceanspy as ospy
%matplotlib inline
od = ospy.open_oceandataset.EGshelfIIseas2km_ASR()
od.TS_diagram(cutout_kwargs={'ZRange': 0, 'timeRange': '2007-09-01', 'dropAxes': True}
```
killaxes

**Review by ThomasHaine — APPROVED** [review]

**Comment by malmans2** [comment]
You can now easily plot timeseries. Here is an example. With one line of code I'm plotting the verticaly integrated zonal velocity in the top 100m for different latitudes:
```python
import oceanspy as ospy
%matplotlib inline
od = ospy.open_oceandataset.EGshelfIIseas2km_ASR()
ax = od.time_series(varName  = 'U',
                    sumAxes  = ['Z'],
                    meanAxes = ['X'],
                    cutout_kwargs={'timeRange': ['2007-09-01', '2007-09-10'], 
                                   'YRange': [ 62,  62.1],
                                   'ZRange': [0, -100]})
```
baro_vel

**Comment by ThomasHaine** [comment]
Suggestions:

TS_diagram computes the density anomaly, even if it's already present. Check if Sigma0 is available and, if so, use it rather than re-compute.

Also: plot Sigma0 contours over the full oceanographic TS range so that subsequently adjusting axis limits avoids the contours ending.

BTW, please remind how to retrieve the latest documentation.

Thanks!

**Comment by malmans2** [comment]
Good timing! I'm almost done with plots and animations:
1. Re-computing Sigma0 sounds like a slowdown, but it's actually faster because a matrix with only 100 Temp and 100 S values is usually enough. If you are plotting a lot of T and S points, using Sigma0 in the dataset would make things slower. I've added another argument  though, which allows to provide a custom DataArray to use for the isopycnals (could be for example `od.dataset['Sigma0']`). It is used for example by the animations, so the isopycnals are only computed once. If for some reason the density matrix automatically computed doesn't work well, then you can provide your own density values. 
2. I'm now computing the freezing point and masking out densities below the freezing point.
3. Using isopycnals for full TS range has some pros and cons. Pros: you can adjust the axis after the plot and see isopycnals in the whole domain. Cons: the isopycnals are not optimized for the TS range of the specific plot (e.g., number of levels, labels outside of the domain), 100x100 T and S values could not be enough.

I think we have two options: 1) Compute Sigma0 for the full oceanographic TS range but also plot the full oceanographic TS range; 2) Keep it like that, and add a note in the documentation that suggests to use `Tlim` and `Slim` rather than `ax.set_xlim` and `ax.set_ylim` after.

What do you think?

**Comment by ThomasHaine** [comment]
Thanks Mattia, See inline below.


Professor Thomas W. N. Haine,
Department of Earth & Planetary Sciences,
329 Olin Hall, The Johns Hopkins University,
Baltimore, MD 21218
Tel.: 410 516 7048
Fax.: 410 516 7933
Thomas.Haine@jhu.edu<mailto:Thomas.Haine@jhu.edu>
http://www.jhu.edu/~eps/faculty/haine

On Mar 3, 2019, at 4:59 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


Good timing! I'm almost done with plots and animations:

  1.  Re-computing Sigma0 sounds like a slowdown, but it's actually faster because a matrix with only 100 Temp and 100 S values is usually enough. If you are plotting a lot of T and S points, using Sigma0 in the dataset would make things slower. I've added another argument though, which allows to provide a custom DataArray to use for the isopycnals (could be for example od.dataset['Sigma0']). It is used for example by the animations, so the isopycnals are only computed once. If for some reason the density matrix automatically computed doesn't work well, then you can provide your own density values.

Good plan. That also allows the user to plot, say, Sigma4 instead of Sigma0.

  1.  I'm now computing the freezing point and masking out densities below the freezing point.

Good plan.


  1.  Using isopycnals for full TS range has some pros and cons. Pros: you can adjust the axis after the plot and see isopycnals in the whole domain. Cons: the isopycnals are not optimized for the TS range of the specific plot (e.g., number of levels, labels outside of the domain), 100x100 T and S values could not be enough.

Understood.


I think we have two options: 1) Compute Sigma0 for the full oceanographic TS range but also plot the full oceanographic TS range; 2) Keep it like that, and add a note in the documentation that suggests to use Tlim and Slim rather than ax.set_xlim and ax.set_ylim after.

What do you think?

I like option 2 better!

**Comment by malmans2** [comment]
I'm always storing the documentation of the last push in the shared folder on SciServer. If you want to make sure that you are reading the documentation associated with your code:
1) Go in the docs folder: `cd ocenaspy/docs`
2) Create the documentation environment: `conda env create -f environment.yml` 
3) Activate the documentation environment `source activate ospy_docs` (depending on the conda version, it might be `conda activate ospy_docs`, the terminal will tell you.
4) Create the documentation `make html` (`make clean` and `rm -r generated/` first if you want to compile from scratch).
5) The documentation is stored under `ocenaspy/docs/_build/html`
6) If you are on SciServer, you can't use the browser. I usually zip the html folder and download it on my laptop.

The terminal shows the name of the active environment. If you do `pip` or `conda install`, then it will install in that environment. So, 
* Make sure you deactivate (or open a new terminal) before installing packages that you need for you base environment (e.g., a new package that you want to use in your notebook) .
* Make sure the `ospy_docs` environment is activated if you need to compile the documentation.

**Comment by ThomasHaine** [comment]
Understood!  Thanks!!


On Mar 3, 2019, at 5:16 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm always storing the documentation of the last push in the shared folder on SciServer. If you want to make sure that you are reading the documentation associated with your code:

  1.  Go in the docs folder: cd ocenaspy/docs
  2.  Create the documentation environment: conda env create -f environment.yml
  3.  Activate the documentation environment source activate ospy_docs (depending on the conda version, it might be conda activate ospy_docs, the terminal will tell you.
  4.  Create the documentation make html (make clean and rm -r generated/ first if you want to compile from scratch).
  5.  The documentation is stored under ocenaspy/docs/_build/html
  6.  If you are on SciServer, you can't use the browser. I usually zip the html folder and download it on my laptop.

The terminal shows the name of the active environment. If you do pip or conda install, then it will install in that environment. So,

  *   Make sure you deactivate (or open a new terminal) before installing packages that you need for you base environment (e.g., a new package that you want to use in your notebook) .
  *   Make sure the ospy_docs environment is activated if you need to compile the documentation.

**Comment by malmans2** [comment]
I've improved the TS diagram. New features:

- use `meanAxes` parameter to compute mean along axes before plotting. E.g., `meanAxes=['Z']`
- compute freezing point using S, and mask out isopycnals below freezing temperature
- use `dens` parameter to provide a DataArray that will be used to plot isopycnals (if not provided, Sigma0 will be computed).

@asiddi24 please review and let me know if anything is missing.

I'm implementing animations. There is a new module named `animate`.
Here is a minimal example:

```python
import oceanspy as ospy
import matplotlib.pyplot as plt
%matplotlib inline
od = ospy.open_oceandataset.EGshelfIIseas2km_ASR()
XRange      = [-45, -18]
YRange      = [ 62,  70]
timeRange =  ['2007-08-29T15:00:00','2007-09-02T00:00:00']
```

- Do you want a static plot? 
```python
ax = ospy.plot.TS_diagram(od, cutout_kwargs={'ZRange': ZRange,
                                             'XRange': XRange,
                                             'YRange': YRange,
                                             'timeRange': timeRange})
```
show_plot

- Do you want an animation? Same code, but use `ospy.animation`:
```python
anim = ospy.animate.TS_diagram(od, cutout_kwargs={'ZRange': ZRange,
                                                  'XRange': XRange,
                                                  'YRange': YRange,
                                                  'timeRange': timeRange})
```
show_animate
Alternatively, you can do `od.TS_diagram(animate=True, ...)` or `od.TS_diagram(animate=False, ...)`
@hooteoos-waltz  please review and let me know if anything is missing.

There are a lot of options! Check out the documentation. Just be aware that scatter plots (activated by `colorName`) can be very slow. You might want to reduce the number of points, for example using `meanAxes`.

One more thing. You need to install a new package in order to use animations. Please create a new container and install from scratch. Installing in a pre-existing container can take forever (I didn't have time to check why). Here is the installation:
```bash
$ conda config --remove channels defaults
$ conda config --add channels conda-forge
$ conda install dask distributed bottleneck netCDF4 xarray cartopy esmpy ffmpeg
$ pip install geopy xgcm xesmf xmitgcm
```
To download the new branch
```bash
$ git clone --single-branch --branch add_plots https://github.com/malmans2/oceanspy.git
```
And install in develop mode
```
$ pip install -e oceanspy/
```

**Comment by malmans2** [comment]
The horizontal plots movies are ready as well. They work as the TS diagram.
Let's use the same cutout used before:
```python
import oceanspy as ospy
import matplotlib.pyplot as plt
%matplotlib inline
od = ospy.open_oceandataset.EGshelfIIseas2km_ASR()
XRange      = [-45, -18]
YRange      = [ 62,  70]
ZRange      = [  0, -30]
timeRange   = ['2007-08-29T15:00:00','2007-09-02T00:00:00']
```
Plot first:
```python
ax = ospy.plot.horizontal_section(od, varName='Temp', contourName='Depth',
                                  meanAxes=['Z'], center=False, robust = True, cmap='viridis',
                                  cutout_kwargs={'ZRange': ZRange,
                                                 'XRange': XRange,
                                                 'YRange': YRange,
                                                 'timeRange': timeRange})
```
multi

And the movie:
```python
anim = ospy.animate.horizontal_section(od, varName='Temp', contourName='Depth', 
                                       meanAxes=['Z'], center=False, robust = True, cmap='jet',
                                       cutout_kwargs={'ZRange': ZRange,
                                                      'XRange': XRange,
                                                      'YRange': YRange,
                                                      'timeRange': timeRange})
```
moviehor

Did you notice that the movie uses Mercator projection? The first plot doesn't project because it's a little hard to make it work with several subplots. If you want subplots and projection, it's better create your own for loop for now.

If your plot doesn't require subplots (e.g., average in time), then oceanspy will use the projection associated with the oceandataset. Do you want to change the projection? Just use `od.set_projection`:
```python
ax = ospy.plot.horizontal_section(od.set_projection('PlateCarree'), varName='Temp', contourName='Depth', plotType='contourf', 
                                  meanAxes=['Z', 'time'], center=False, cmap='hot',
                                  cutout_kwargs={'ZRange': ZRange,
                                                 'XRange': XRange,
                                                 'YRange': YRange,
                                                 'timeRange': timeRange})
ax.set_title('PlateCarree')
```
plate
 
Or just switch the projection off
```python
ax = ospy.plot.horizontal_section(od.set_projection(None), varName='Temp', contourName='Depth', 
                                  sumAxes=['Z'], center=False,  cmap='inferno',
                                  contour_kwargs={'levels': [100, 200, 500, 600, 1000]},
                                  cutout_kwargs={'ZRange': ZRange,
                                                 'XRange': XRange,
                                                 'YRange': YRange,
                                                 'timeRange': timeRange[0],
                                                 'dropAxes': True})
ax.set_title('No Projection')
```
noproj
High temperature values because I'm summing on the Z axis now.

I've only shown a few options, hopefully everything is in the documentation!

**Comment by malmans2** [comment]
Vertical sections done! 
```python
import oceanspy as ospy
import matplotlib.pyplot as plt
%matplotlib inline
od = ospy.open_oceandataset.EGshelfIIseas2km_ASR()
lats_Kogur = [ 68.68,  67.52,  66.49]
lons_Kogur = [-26.28, -23.77, -22.99]
timeRange   = ['2007-08-29T15:00:00','2007-09-02T00:00:00']
```

Plot:
```python
ax = ospy.plot.vertical_section(od, varName='Temp', subsampMethod='survey_stations', contourName='Sigma0',
                                center=False, robust = True,
                                subsamp_kwargs={'Xsurv': lons_Kogur,
                                                'Ysurv': lats_Kogur,
                                                'ZRange': [0, -1600],
                                                'timeRange': timeRange,
                                                'dropAxes': 'time',
                                                'delta': 2,
                                                'varList': ['Temp', 'S']})
```
vsec

Animation:
```python
anim = ospy.animate.vertical_section(od, varName='Temp', subsampMethod='survey_stations', contourName='Sigma0',
                                     center=False, robust = True,
                                     subsamp_kwargs={'Xsurv': lons_Kogur,
                                                     'Ysurv': lats_Kogur,
                                                     'ZRange': [0, -1600],
                                                     'timeRange': timeRange,
                                                     'dropAxes': 'time',
                                                     'delta': 2,
                                                     'varList': ['Temp', 'S']})
```
vsec_movie

**Comment by malmans2** [comment]
Plots need some minor fix, and I need to clean up a little the code, but they're pretty much ready.
I'm going to merge with master!

**Pull request merged**
