### PR TITLE
Pin cartopy

### PR DESCRIPTION
**Pull request by malmans2**
See #197

### CODE REVIEW

**Comment by Mikejmnez** [comment]
Great! Let's wait before merging. We are in the process of updating the image in Sciserver. We should make there is no other issues with other packages. Ali and I are checking in tomorrow ...

**Comment by malmans2** [comment]
Got it!
The current SciServer environment is [here](https://github.com/hainegroup/oceanspy/blob/master/sciserver_catalogs/environment.yml). I think you can combine that one with [this one](https://github.com/malmans2/oceanspy/blob/pin_cartopy/ci/environment.yml) (using the versions specified in the latter), and just add any additional package you need. If it's of use, I'm often installing a few additional packages in my workflows, [here](https://github.com/malmans2/conda-envs/blob/main/complete.yml) is the environment I use.

Also we usually make a new release when we update the image. Let me know if you want to release and when you are ready. We might have to update a bit the workflow before releasing... I'll take a look.

**Comment by Mikejmnez** [comment]
Awesome, thanks! @asiddi24 and I will look into this. I have more revisions/additions to ```llc_rearrange.py``` to increase its speed and efficiency (plus more testing) in the next couple of weeks. Lets wait to do a new release after that.

**Comment by Mikejmnez** [comment]
Closing this, since PR #222 includes the changes here

**Pull request closed without merging**
