### PR TITLE
Complete tests

### PR DESCRIPTION
**Pull request by malmans2**
* OceanDataset, opening, subsampling, and computing fully tested (99%)
* More robust calculus with units, error messages for wrong fields (e.g., laplacian for vectors), weighted means and integrals using the same functions, integral and weighted means available for every axis.
* Almost everyting is tested using aliases as well

I've excluded plot and animation from the codecoverage report, I'll work and finish it on Friday.

### CODE REVIEW

**Comment by malmans2** [comment]
Also, SAMS data available in open_oceandataset! I didn't really check it out though.

**Comment by malmans2** [comment]
* Fully tested
* Following PEP8 style guide
* Opening using catalogs

TODO:
* Update docs
* Add missing attributes (I would like to use the same attributes used by xmitgcm)

**Comment by malmans2** [comment]
@ThomasHaine @renskegelderloos @hooteoos-waltz @renskegelderloos please start using this version and let me know if I can merge.
 The new syntax to open oceandatasets on SciServer is   
`od = ospy.open_oceandataset.from_catalog('name')`.  
Available od are:
* `'get_started'`
* `'EGshelfIIseas2km_ERAI_6H'`
* `'EGshelfIIseas2km_ERAI_1D'`
* `'EGshelfIIseas2km_ASR_full'`
* `'EGshelfIIseas2km_ASR_crop'`
* `'Arctic_Control'`
* `'KangerFjord'`
* `'EGshelfSJsec500m_3H_hydro'`
* `'EGshelfSJsec500m_6H_hydro'`
* `'EGshelfSJsec500m_3H_NONhydro'`
* `'EGshelfSJsec500m_6H_NONhydro'`

**Comment by malmans2** [comment]
To download this branch: `git clone --single-branch --branch complete_tests https://github.com/malmans2/oceanspy.git`
[This](https://github.com/malmans2/oceanspy/blob/f9e4cc824ef60677ba091994e6d82fe9161b5744/ci/environment-py36.yml) is the environment that I'm currently using and is passing the tests. You can use the yml file to [create a different environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file), or manually install packages using conda install. If you have an old version of conda, I suggest to update it first. The most important news are: 
- `xgcm` must be >=0.2
- you need `intake-xarray`
- `xmitgcm` needs to be installed from github

We haven't fixed the oceanography image on SciServer yet, so you need to update it by yourself.
Once everything is installed, `pip install -e oceanspy/`.
If you have all the tests packages installed and you want to test oceanspy, I suggest `cd oceanspy/`, then `py.test oceanspy -v --cov=oceanspy --cov-config .coveragerc --cov-report term-missing
`. It will show the coverage as well.

**Comment by ThomasHaine** [comment]
I tried using the yml file to build the new environment. I hit errors with:

[idies@8d4f4cd3e9eb persistent]$ conda env create -f enviroment-py36.yml
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - xesmf -> esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> libgcc-ng[version='>=7.3.0']
  - xesmf -> esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - xesmf -> esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> libstdcxx-ng[version='>=7.3.0']
  - xesmf -> esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> openmpi[version='>=3.1,<3.2.0a0']
  - xesmf -> esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> mpich[version='>=3.2,<3.3.0a0']
  - xesmf -> esmpy -> esmf=7.1.0 -> libnetcdf[version='>=4.6.2,<4.7.0a0'] -> jpeg[version='>=9c,<10a']
  - xesmf -> esmpy -> esmf=7.1.0 -> netcdf-fortran[version='>=4.4.5,<4.5.0a0']
  - xesmf -> esmpy -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - xesmf -> esmpy -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.26.0,<4.0a0']
  - xesmf -> esmpy -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
  - xesmf -> esmpy -> python[version='>=3.7,<3.8.0a0'] -> xz[version='>=5.2.4,<5.3.0a0']
  - esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> libgcc-ng[version='>=7.3.0']
  - esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> libstdcxx-ng[version='>=7.3.0']
  - esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> openmpi[version='>=3.1,<3.2.0a0']
  - esmpy -> esmf=7.1.0 -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> mpich[version='>=3.2,<3.3.0a0']
  - esmpy -> esmf=7.1.0 -> libnetcdf[version='>=4.6.2,<4.7.0a0'] -> jpeg[version='>=9c,<10a']
  - esmpy -> esmf=7.1.0 -> netcdf-fortran[version='>=4.4.5,<4.5.0a0']
  - esmpy -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - esmpy -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.26.0,<4.0a0']
  - esmpy -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
  - esmpy -> python[version='>=3.7,<3.8.0a0'] -> xz[version='>=5.2.4,<5.3.0a0']

Ideas to fix this?

Thanks!  T

**Comment by malmans2** [comment]
Not sure why the installation from yml works with Rossby and the continuous integration service, but gives errors on SciServer (and my laptop). I think it has to do with the the version of conda and the way packages have been previously intalled. You can do this for now:
1. Create a new container with the Oceanography image
2. Upgrade xarray and xgcm: `$ pip install xarray xgcm --upgrade`
4. Uninstall xmitgcm and oceanspy: `$ pip uninstall xmitgcm oceanspy` 
5. Install xmitgcm from github: `$ pip install git+https://github.com/xgcm/xmitgcm.git`
6. Install intake-xarray: `$ conda install -c conda-forge intake-xarray`
7. Install tests and docs packages: `$ pip install pytest pytest-cov pytest-env codecov numpydoc sphinx sphinx_rtd_theme nbsphinx`
8. Download the latest branch of OceanSpy: `$ git clone --single-branch --branch complete_tests https://github.com/malmans2/oceanspy.git`
9. Go into the oceanspy folder: `$ cd oceanspy/`
10. Install OceanSpy: `$ pip install -e .`
11. Test: `$ py.test oceanspy -v --cov=oceanspy --cov-config .coveragerc --cov-report term-missing`

If the installation from .yml doesn't work on your Mac, I think you can do the same on your laptop (after installing OceanSpy using [this](https://oceanspy.readthedocs.io/en/latest/installation.html#install-oceanspy-from-terminal)).

**Comment by ThomasHaine** [comment]
This works.



On Apr 7, 2019, at 9:50 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure why the installation from yml works with Rossby and the continuous integration service, but gives errors on SciServer (and my laptop). I think it has to do with the the version of conda and the way packages have been previously intalled. You can do this for now:

  1.  Create a new container with the Oceanography image
  2.  Upgrade xarray and xgcm: $ pip install xarray xgcm --upgrade
  3.  Uninstall xmitgcm and oceanspy: $ pip uninstall xmitgcm oceanspy
  4.  Install xmitgcm from github: $ pip install git+https://github.com/xgcm/xmitgcm.git
  5.  Install intake-xarray: $ conda install -c conda-forge intake-xarray
  6.  Install tests and docs packages: $ pip install pytest pytest-cov pytest-env codecov numpydoc sphinx sphinx_rtd_theme nbsphinx
  7.  Download the latest branch of OceanSpy: $ git clone --single-branch --branch complete_tests https://github.com/malmans2/oceanspy.git
  8.  Go into the oceanspy folder: $ cd oceanspy/
  9.  Install OceanSpy: $ pip install -e .
  10. Test: $ py.test oceanspy -v --cov=oceanspy --cov-config .coveragerc --cov-report term-missing

If the installation from .yml doesn't work on your Mac, I think you can do the same on your laptop (after installing OceanSpy using this<https://oceanspy.readthedocs.io/en/latest/installation.html#install-oceanspy-from-terminal>).

**Comment by malmans2** [comment]
Address #72

**Comment by malmans2** [comment]
This works for me:
* Create a container using the Oceanography image
* Go in the `persistent` directory (where I don't have any oceanspy repository)
* Update old packages and install new: `conda install -y dask distributed bottleneck netCDF4 xarray cartopy esmpy ffmpeg intake-xarray tqdm geopy xgcm xesmf`
* Install xmitgcm from master: `pip install --no-deps --force-reinstall git+https://github.com/xgcm/xmitgcm.git`
* Clone oceanspy: `git clone --single-branch --branch final_dev https://github.com/malmans2/oceanspy.git`
* Enter oceanspy repository `cd oceanspy/`
* Install oceanspy: `pip install -e .`
* Test oceanspy: `pytest oceanspy`
```
oceanspy/tests/test_animate.py ..........                                                                           [  1%]
oceanspy/tests/test_compute_calculus.py ........................................................................... [ 13%]
..                                                                                                                  [ 14%]
oceanspy/tests/test_compute_functions.py .......................................................................... [ 26%]
...                                                                                                                 [ 26%]
oceanspy/tests/test_oceandataset.py ............................................................................... [ 39%]
................................................................................................................... [ 58%]
..............                                                                                                      [ 60%]
oceanspy/tests/test_open_oceandataset.py .......                                                                    [ 62%]
oceanspy/tests/test_plot.py ....................................................................................... [ 76%]
.............................................................                                                       [ 86%]
oceanspy/tests/test_subsample.py .................................................................................. [ 99%]
                                                                                                                    [ 99%]
oceanspy/tests/test_utils.py ..                                                                                     [100%]

============================================== 611 passed in 421.45 seconds ===============================================
```

**Pull request closed without merging**
