### PR TITLE
add llc4320 forcing files to catalog

### PR DESCRIPTION
**Pull request by Mikejmnez**
I have transformed the forcing files into zarr from binary and are now available through Sciserver. I have added an entry on the intake catalog to load them when reading llc4320 data.

### CODE REVIEW

**Comment by Mikejmnez** [comment]
I don't understand the formatting error at all. When I run 
```python
pre-commit run --all
```
I get all `passed`. I reverse the changes but I don't think it triggered pre-commit to run again. Will make a change and reverse it, just to see if things change,

**Comment by Mikejmnez** [comment]
I removed the catalog entry and the error persisted. Again, running on my computer ```pre-commit run --all``` I don't ger any error, and all things pass. 

Here is a snapshot of what it is:

error

I will approve the PR, since the error is not associated with the change to the catalog entry I made.

Will be on the lookout if this happens again. If so, will raise and issue and inspect it.

**Comment by ThomasHaine** [comment]
Thanks @Mikejmnez !  So the forcing files are now available through the regular `open_oceandataset`?  And sea ice files?

**Comment by Mikejmnez** [comment]
Yes. All forcing files that we have for the 10 day test (hourly) LLC4320 data are available by doing

```python
od = ospy.open_oceandataset.from_catalog('LLC4320')
```

The added variables are:

```python
['oceFWflx', 'oceQnet', 'oceQsw', 'oceSflux', 'oceTAUX', 'oceTAUY', 'SIarea', 'SIheff', 'SIhsalt', 'SIhsnow', 'SIuice', 'SIvice', 'KPPhbl']
```

I will add the vertical velocity W soon too. In that case no PR will be needed.

**Pull request merged**
