### PR TITLE
Fix all paths and environment

### LINKED ISSUE #127: Migration Box to OneDrive
See email below. All our test datasets are currently hosted by Box. Let's keep an eye on the migration and, when it's done, switch the shared links from Box to OneDrive:

> IT at Johns Hopkins is ending their agreement with Box and will be using Microsoft OneDrive as their new online storage provider. As part of this change, all data currently in your Box account will be migrated to OneDrive. Data will be migrated to OneDrive in two phases. The first phase will copy all existing data from Box to OneDrive, and Box will continue to function normally. The second phase will be a “copy changed files” and write access to Box WILL STOP when this copy is complete. This means that no new data can be added to Box after the second copy finishes, and files must be shared out to others using OneDrive. All Box accounts will be terminated in April of 2020.
> 
>  
> Important things to note:
> 
> ***Any files in Box which are shared will have to be shared out again once copied over to OneDrive.  (Since external collaborations will not be recreated, a report will be provided for users to review all external collaborations which can be recreated once the migration/copy is completed)
> 
> ***Any file/folder structure exceeding 350 characters will not be migrated/copied to JHOneDrive.
> 
>  
> 
> Members of the Krieger School of Arts and Sciences will begin the migration on November 14th.

### LINKED ISSUE #128: ImportError due to ESMF
Travis-CI is reporting the following error:
ImportError: Regrid(filename) requires PIO and does not work if ESMF has not been built with MPI support

It looks like adding `esmf` in the `environment.yml` files fixes the problem.

### PR DESCRIPTION
**Pull request by malmans2**
- [x] Closes #127 
- [x] Closes #128

### CODE REVIEW

**Comment by malmans2** [comment]
This is good to go! I checked all notebooks on SciServer. I just need someone to review.

**Comment by malmans2** [comment]
Travis-CI is failing because OneDrive is temporarily down. I'll restart the tests later.

**Comment by malmans2** [comment]
All set! Python 3.8 was released last month, so we are now testing it as well. I only had to make a minor compatibility change.

**Review by ThomasHaine — APPROVED** [review]
Looks good!

**Pull request merged**
