### PR TITLE
For very old issues

### PR DESCRIPTION
**Pull request by MaceKuailv**
Hopefully resolves issue #70 and #136. Both solved by giving comments, elegant error messages and a tiny change on the code

### CODE REVIEW

**Comment by MaceKuailv** [comment]
we still get 

 AttributeError: 'GeoAxesSubplot' object has no attribute '_autoscaleXon'


This is a bit beyond me

**Comment by MaceKuailv** [comment]
me and the robots are on the same boat now

**Comment by ThomasHaine** [comment]
Try to make a minimum working example that replicates the error. Once that's done, consult @Mikejmnez and @malmans2 on details (and me on strategy, if needed).

**Comment by MaceKuailv** [comment]
The plot.horizontal_section function is broke by this cartopy dependency. 

I didn't change the pinning of cartopy when I set up the environment and install the package. So, here is an example.
```
import oceanspy as ospy

od = ospy.open_oceandataset.from_catalog('get_started')
# od._ds['s_top'] = od._ds['S'][0,0] # this is 
od.plot.horizontal_section(varName = 'XC')
```
You should be getting an error that says "AttributeError: 'GeoAxesSubplot' object has no attribute '_autoscaleXon' ".

This error is very easy to reproduce as you can see.

**Comment by ThomasHaine** [comment]
@MaceKuailv, I run your code snippet on SciServer with a fresh Oceanography console and get no AttributeError.

**Comment by MaceKuailv** [comment]
@ThomasHaine thanks, this is good to know. 

I think @Mikejmnez resolved this last night... Apparently, all tests are passing in his pull request but not in mine and the bots'. 

I am not sure which part causes it.

**Comment by Mikejmnez** [comment]
> 

We just looked into this me and @MaceKuailv , and the environment used for ci testing in my PR (which passed all tests) installed matplotib version 3.3.5. @MaceKuailv will then pin matplotlib to a version <=3.5.2 and see if this helps with testing...

**Comment by Mikejmnez** [comment]
@MaceKuailv don't forget to sync your fork with the new changes I added to oceanspy, so that your PR does not revert them...

**Review by ThomasHaine — APPROVED** [review]
Ready to commit once the latest code is synced and the tests pass...

**Pull request closed without merging**
