### PR TITLE
Migrate to GH actions and pre-commit

### LINKED ISSUE #171: Migrate CI
We should migrate CI from Travis to GitHub actions as the free plan of Travis changed.

### PR DESCRIPTION
**Pull request by malmans2**
Close #171

### CODE REVIEW

**Comment by malmans2** [comment]
All set. We're also building readthedocs at each PR to check the docs. Is not showing up in the checks though, so I have to figure it out. Must be a permission issue.

**Comment by malmans2** [comment]
@ThomasHaine you should get an email from readthedocs

**Review by ThomasHaine — APPROVED** [review]
Looks good to merge. I've approved the readthedocs access request.

**Comment by malmans2** [comment]
Merging!

**Pull request merged**
