### PR TITLE
Add daily mean ecco dataset to catalog

### PR DESCRIPTION
**Pull request by MaceKuailv**
Add the catalog for daily ecco

### CODE REVIEW

**Comment by Mikejmnez** [comment]
The error in CI you are getting is related to issue #332 , independent of the changes within this PR.

I got another fix for the issue in #332 , but I am having some trouble trying to install a testing environment in Sciserver to check that the error goes away. Mitya is helping me, hopefully will get a PR fixing issue #332 later today...

**Review by Mikejmnez — APPROVED** [review]

**Comment by Mikejmnez** [comment]
@MaceKuailv don't forget to run pre-commit to get all the formatting right

**Comment by MaceKuailv** [comment]
I am doing the pre-commit right now. I didn't realize that this part also have format constraints.

**Comment by ThomasHaine** [comment]
Thanks @MaceKuailv and @Mikejmnez!  I'll make an announcement on https://www.poseidon-ocean.net/.

**Pull request merged**
