### PR TITLE
Final dev

### PR DESCRIPTION
**Pull request by malmans2**
@hooteoos-waltz @renskegelderloos @asiddi24 @ThomasHaine 
I've been trying some stuff on #63 that it's better to keep separate. The new tests download data from my box, so I was trying the commands to remove .nc and .data files from the git history (I didn't proceed yet, but I will in the future). This will keep the oceanspy repository on github lighter. From now on please use this branch (which is exactly the same of #63, but with the whole git history). 
Sorry about any confusion! 
I just started to update the docs and I will add commits here, then I think we should merge with the master branch.

### CODE REVIEW

**Comment by malmans2** [comment]
@pep8speaks suggest diff

**Comment by malmans2** [comment]
I think we should merge this PR.
* closes #15 
* closes #40 
* closes #62 
* closes #64 
* closes #66 
* closes #72

**Comment by malmans2** [comment]
The new tutorial and tests can be executed on SciServer and on any workstation. We haven't updated the oceanography image on SciServer yet. As explained in the new documentation, just do this when you open the Oceanography image:
```bash
conda install -y dask distributed bottleneck netCDF4 xarray cartopy esmpy ffmpeg intake-xarray tqdm geopy xgcm xesmf
pip install --no-deps --force-reinstall git+https://github.com/xgcm/xmitgcm.git
```
Then download the latest oceanspy version (this or from master once we merge) and install it.

To test on SciServer, just go into the oceanspy repository and use `pytest oceanspy`. On other workstations, you shouldn't have problems with `conda env create -f` and you can run the exact same tests and coverage reports used by the continuous integration (see the section contributing in the documentation).

**Comment by renskegelderloos** [comment]
@malmans2 
How long is pytest oceanspy supposed to take on SciServer? It seems to get stuck at 62%.

**Comment by renskegelderloos** [comment]
@malmans2 
It appears the compute function mooring_horizontal_volume_transport no longer exists, and is replaced by mooring_volume_transport, is that correct? The tab functionality still gives the first option, which is weird, and then gives an error that that method does not exist. The second methods does work.

**Comment by malmans2** [comment]
It should take around 10min total. Yes, I think that's the only syntax I changed, because the old one was to long. I'm not sure why you are seeing both old and new stuff. I just run the tests and tried tab and I don't have the same problem. Are you installing with `pip install -e`?

**Comment by malmans2** [comment]
closes #53

**Comment by malmans2** [comment]
The tutorial notebook that will show up in the documentation is under `docs/Tutorial.ipynb`

**Comment by renskegelderloos** [comment]
Yes, I cloned the branch final_dev and installed with pip install -e .

**Comment by malmans2** [comment]
@renskegelderloos This works for me:
* Create a container using the Oceanography image
* Go in the `persistent` directory (where I don't have any oceanspy repository)
* Update old packages and install new: `conda install -y dask distributed bottleneck netCDF4 xarray cartopy esmpy ffmpeg intake-xarray tqdm geopy xgcm xesmf`
* Install xmitgcm from master: `pip install --no-deps --force-reinstall git+https://github.com/xgcm/xmitgcm.git`
* Clone oceanspy: `git clone --single-branch --branch final_dev https://github.com/malmans2/oceanspy.git`
* Enter oceanspy repository `cd oceanspy/`
* Install oceanspy: `pip install -e .`
* Test oceanspy: `pytest oceanspy`
```

**Comment by ThomasHaine** [comment]
I see some variables and their associated weights with nan, which is new. E.g.

    momVort3            float64 nan
    Ertel_PV            float64 nan
    Okubo_Weiss         float64 nan
    w_mean_momVort3     float64 nan
    weight_momVort3     float64 nan
    w_mean_Ertel_PV     float64 nan
    weight_Ertel_PV     float64 nan
    w_mean_Okubo_Weiss  float64 nan
    weight_Okubo_Weiss  float64 nan

**Comment by malmans2** [comment]
Can you please share some code to reproduce the error?
This code works for me:
```python
import oceanspy as ospy
od = ospy.open_oceandataset.from_catalog('get_started')
ds = ospy.compute.weighted_mean(od, 'Ertel_PV')
print(ds['w_mean_Ertel_PV'].values)
```
and returns 3.8779311765221984e-10

**Comment by ThomasHaine** [comment]
The code is attached. I don’t get nans with EGshelfIIseas2km_ASR_full but I do with getting_started. I guess they’re all inherited from momVort3?



On Apr 18, 2019, at 12:24 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please share some code to reproduce the error?
This code works for me:

import oceanspy as ospy
od = ospy.open_oceandataset.from_catalog('get_started')
ds = ospy.compute.weighted_mean(od, 'Ertel_PV')
print(ds['w_mean_Ertel_PV'].values)


and returns 3.8779311765221984e-10

**Comment by malmans2** [comment]
Yes, my guess is also that the problem is coming from the relative vorticity.
I didn't get your attachment. Maybe github doesn't include attachments from emails?

**Comment by ThomasHaine** [comment]
Sorry!  Here's a MWE. The cutout is important.

```
import oceanspy          as ospy
od          = ospy.open_oceandataset.from_catalog('get_started')
timeRange   = ['2007-08-29T15:00:00','2007-10-02T00:00:00']
XRange      = [-40, -22]
YRange      = [ 63,  67]
ZRange      = [-100,   0]
od_snapshot = od.subsample.cutout(varList=['Temp','S','U','V','W',
                                 'fCoriG',
                                 'rA','rAz','rAs','rAw',
                                 'dxC','dxF','drC',
                                 'dyC','drF','dyF',
                                 'dxG','dyG','dyU','dxV',
                                 'HFacC','HFacW','HFacS',
                                 'Depth'],
                        timeRange=timeRange,
                        XRange   =XRange,
                        YRange   =YRange,
                        ZRange   =ZRange)
od_snapshot = od_snapshot.compute.vertical_relative_vorticity()
var_mean    = od_snapshot.dataset.mean(keep_attrs=True).load()
var_mean
```

**Comment by malmans2** [comment]
The problem is that you are cutting out a region which is outside of the `get_started` domain (there should be warnings that tell you about it). The current `get_started` domain is the same of `EGshelfIIseas2km_ASR_crop`, so it can be used for budgets as well. It's also just 1 day (4 snapshots). The relative vorticity gives nans because the cutout U only has 1 point on the y dimension, and V only has 1 point on the x dimension.

**Review by ThomasHaine — APPROVED** [review]
Looks good to me!

**Pull request merged**
