### PR TITLE
Revert "loading ECCO v4r4 in zarr format "

### PR DESCRIPTION
**Pull request by malmans2**
Reverts hainegroup/oceanspy#200

@asiddi24 #200 might need some thoughts. I'm opening a revert PR, just in case...
We can close if everything looks good.

There's a few things to check in #200:
- [x] It breaks different tests, so there might be something to fix in that PR
- [x] It breaks the documentation
- [x] Doesn't pass pre-commit, try to run this locally `pre-commit run --all`

### CODE REVIEW

**Comment by Mikejmnez** [comment]
I checked quickly PE #200. Yes, indeed it is breaking some basic tests. The line that is causing some trouble in open_oceandataset is

```python
ds = ds.drop_vars(["k_p1", "k_u", "k_l", "k"])
```
It is not finding some of these variables... It could be related with the dataset that is being used for testing. For now just comment this line. There is some funny behavior here. 

Like Mattia says, running

```python
pre-commit run --all
```
should fix the formatting issues. The only issue is really a single whitespace in the intake catalog.


And lastly, the documentation is breaking because it is not recognizing [ECCO] in the docs/conf.py file.

 Perhaps setting it back to ECCO (insterad of ECCOv4) will work?


Screen Shot 2022-02-14 at 5 01 34 PM
as a dataset.

**Comment by asiddi24** [comment]
Yeah, it is the line in `open_oceandataset` that's failing it. 

>Perhaps setting it back to ECCO (insterad of ECCOv4) will work?

Will do.

**Comment by asiddi24** [comment]
okay, looks like the checks are now being passed better than in #200. @malmans2 this checks all 3 concerns ? @Mikejmnez does it look good now ?

**Comment by malmans2** [comment]
> okay, looks like the checks are now being passed better than in #200. @malmans2 this checks all 3 concerns ? @Mikejmnez does it look good now ?

Yup! Wait for @Mikejmnez approval to merge, but CI looks good. (Is this superseding #200? I.e., all changes you made in #200 are now here?)

**Comment by asiddi24** [comment]
All changes in #200 are here.

**Review by Mikejmnez — APPROVED** [review]

**Pull request merged**
