### PR TITLE
loading ECCO v4r4 in zarr format 

### PR DESCRIPTION
**Pull request by asiddi24**
I've added the ECCO v4r4 intake catalog entry and removed the test data. Grid is not added separately since the dataset was stored with the grid added to it in the merged dataset. Added grid arguments though to the catalog entry. 

The data loads super quick with the zarr format, granted it's about 145 GB. Following up on #168, there needs to be something of the sorts `xarray_kwargs` in the `xr.open_zarr` functionality. 

All looks good. Will update #168 with changes as well.

### CODE REVIEW

**Comment by asiddi24** [comment]
need to correct for failing tests

**Comment by ThomasHaine** [comment]
What's the status of this PR?  Can we fix and merge soon?  I'm posting to the Poseidon website about ECCO functionality in OceanSpy+SciServer.

**Review by ThomasHaine — APPROVED** [review]
Looks good to me!  We should add an ECCO tutorial so folks can get going with these data quickly.

**Comment by Mikejmnez** [comment]
@asiddi24 The error looks pretty easy to fix. It looks like it has to do with an incompatibility between the new line 

```python
ds = ds.drop_vars(["k_p1", "k_u", "k_l", "k"])
```
when creating the test ospy dataset, and the data (along with .yaml file) used for testing. The error you are getting is

```python
ValueError: One or more of the specified variables cannot be found in this dataset
```

(you can see this in lines 11681-11689 of the CI/Build). I think the easier fix would be to update the data for testing (I used `ECCO_v4/THETA/THETA_1992_01.nc`, `.../UVEL_1992_01.nc`,  `.../VVEL_1992_01.nc` and the `ECCO_grid.nc` files) along with the `catalog_ECCO.yaml` to read them, in a way that is compatible with the format of the ECCO dataset that will be used on Sciserver...

**Comment by ThomasHaine** [comment]
@asiddi24 Is this PR ready for merge?  Once the failing tests are fixed (which seems to be a universal issue with all PRs at the moment)?

**Comment by asiddi24** [comment]
tests are failing, but for now I'm going to go ahead and merge. This is so that we can test the new oceanography image.

**Comment by malmans2** [comment]
@asiddi24 don't delete this branch until we decide what to do with #217

**Comment by asiddi24** [comment]
got it

**Pull request merged**
