### PR TITLE
enhancing LLC rearrange

### LINKED ISSUE #223: LLC cutout with varList = None
* OceanSpy version: 0.2.0

### Description

I was trying to make a cutout on the ECCO dataset in the ./oceanspy/tests/ECCO directory. I did almost the same thing as the test_subsample:

```
od_cut = od.subsample.cutout(
             XRange=[-90, 20],
             YRange=[20, 80],
             ZRange=None,
             transformation = 'arctic_crown',
             centered = 'Atlantic'
       )
```
The error message was 
```
File ~/workspace/Temporary/wenrui/scratch/oceanspy/oceanspy/llc_rearrange.py:106, in LLCtransformation.arctic_crown(self, ds, varlist, centered, faces, chunks, drop)
    104 for i in range(len(ARCT)):
    105     if type(ARCT[i][0]) == _datype:
--> 106         ARCT[i] = _xr.merge(ARCT[i])
    108 DSa2, DSa5, DSa7, DSa10 = ARCT
    109 if type(DSa2) != _dstype:

File ~/miniconda3/envs/oceanspy_test/lib/python3.10/site-packages/xarray/core/merge.py:892, in merge(objects, compat, join, fill_value, combine_attrs)
    890 for obj in objects:
    891     if not isinstance(obj, (DataArray, Dataset, dict)):
--> 892         raise TypeError(
    893             "objects must be an iterable containing only "
    894             "Dataset(s), DataArray(s), and dictionaries."
    895         )
    897     obj = obj.to_dataset(promote_attrs=True) if isinstance(obj, DataArray) else obj
    898     dict_like_objects.append(obj)

TypeError: objects must be an iterable containing only Dataset(s), DataArray(s), and dictionaries.
```
If I include varList = ['T'] in the argument, the message will be gone. I think this is likely because the LLC_rearrange assumes that there is no DataArray to rearrange when the varList is None. What it should assume is that all of the arrays are being transformed, to be consistent with the rest of the subsampling package.

### LINKED ISSUE #266: consolidate XRange and YRange correct evaluation
### Description

The introduction of LLC geometry and idea of periodic domain (as opposed to full domain defined defined only in subpolar North Atlantic) has led to some issues regarding cutouts that, over time, we have patched here and there. These are documented in the closed issues #256 and #215. I will briefly described how we patched those issues and how these lead to inconsistencies.

Some basic definitions. The python arrays ```XRange``` and ```YRange``` have the following form:

```python
XRange = [X_0, ..., X_f]
YRange = [Y_0, ..., Y_f]
```
where the subscripts ```0``` and ```f``` meant to represent the zeroth (e.g. first) station and the final (last) sampling station, respectively.

On issue #256.
Renske showed a nice example of what the problem is there, when extracting mooring and survey stations from an array of lats and lons. This is, the issue at hand was in ```od.subsample.survey_stations``` and ```od.subsample.mooring_array``` and how the ranges where passed on to cutout. 

Here I provide another one, describing also the patchwork.
Consider WOCE section **A03** extracted from the (official website). The ship track begins in Europe and ends in NorthAmerica. See plot below

Screen Shot 2022-10-18 at 10 02 19 AM

As visible implies that ```X_0 < X_f``` and furthermore ```Y_f > Y_0 > np.min(YRange)```. Thus simply extracting the pairs ```XRange[0], XRange[-1]``` and ```YRange[0], YRange[-1]``` and passing them into cutout produces no cutout.

The bug, as Resnke pointed out, indeed lies in the following snippet within ```get_maskH```
```python
if XRange is not None:
        # Use arrays
        XRange = _np.asarray([XRange[0] - add_Hbdr, XRange[-1] + add_Hbdr])
        XRange = XRange.astype(ds["XG"].dtype)
```
Note that for ```YRange```, the max and min are taken instead. The original reason to not take min and max of ```XRange``` was associated with the discontinuity of longitude in the LLC geometry. However, as described above, simply taking the first and last can yield to errors. More on the discontinuity below.

The solution as described in #256, was to only pass the max and mins of a given array of lats and lons from ```survey_stations``` or ```mooring_arrays``` into ```.cutout```. This is the actual code snippet (lines 693-699 in subsample.py) below:

```python
    if "YRange" not in kwargs:
        kwargs["YRange"] = [_np.min(Ymoor), _np.max(Ymoor)]
    if "XRange" not in kwargs:
        kwargs["XRange"] = [_np.min(Xmoor), _np.max(Xmoor)]
    if "add_Hbdr" not in kwargs:
        kwargs["add_Hbdr"] = True
    od = od.subsample.cutout(**kwargs)
```

This solved the issue when the cutout is performed from either ```.survey_station``` or ```.mooring_array```, but my guess is that it remains in cutout (i.e. pass an array directly into ```od.subsample.cutout```). 

So far the fix in #256 has worked but because no one is looking at cutouts (moorings, surveys) in the Pacific Ocean across the discontinuity in Longitude. Under such scenario simply taking the min and max of ```XRange``` would yield the wrong region of the world. 

This discontinuity in Longitude due to the periodic domain in LLC grids was solved by Wenrui a while back (solved issue #215). He wrote a function called ```rel_lon```. This worked really nicely but it has come to my attention while making regional cutout across the Pacific ocean ```rel_lon``` is only applied within ```subsample.cutout```. 
This is, taking the min and max of XRange within ```survey_stations``` or ```mooring_array``` for an array across the discontinuity will yields either the wrong domain, or no domain.

### Solution
I think the solution should be simple. Revert how mooring_array and survey_stations pass XRange and YRange into cutout, so pass the whole array. This is how things were done before. It should look like

```python
    if "YRange" not in kwargs:
        kwargs["YRange"] = Ymoor
    if "XRange" not in kwargs:
        kwargs["XRange"] = Xmoor
    if "add_Hbdr" not in kwargs:
        kwargs["add_Hbdr"] = True
    od = od.subsample.cutout(**kwargs)
```
and also within ```get_maskH``` revert to

```python
if XRange is not None:
        # Use arrays
        XRange = _np.asarray([_np.min(XRange) - add_Hbdr, _np.max(XRange[-1]) + add_Hbdr])
        XRange = XRange.astype(ds["XG"].dtype)
```

That way ```rel_lon`` only needs to and is evaluated within ```subsample.cutout```, and the edges of XRange and YRange are consistently defined throughout.

### PR DESCRIPTION
**Pull request by Mikejmnez**
This new PR improves the efficiency of `llc_rearrange` by allowing it to **transform** only the data relevant to the range of lats and long defined within `subsample.cutout`. That is, `llc_rearrange` takes the arguments

```python
XRange = np.array, list or None.
YRange = np.array, list or None.
```

This is, llc_rearrange identifies the cutout region, and only transforms it returning a new dataset without complex topology.  The older version of `llc_rearrange` would transform first all the data within the faces that contain the XRange and YRange values, and then drop most of it... See the example below, wherein the blue region in the map describes the cutout region when XRange and YRange (defined by A05 data). llcrearrange transforms the smallest rectangle containing such data, as opposed to first transforming the faces with "surviving data".

Screen Shot 2022-10-23 at 9 59 12 PM

I was going to create this pull request on Friday, but then I noticed a weird behavior when `XRange` and `YRange` define a region entirely in the Pacific Ocean. The cutout performs exactly as it should be, but the ordering of the indexes is reversed. I will open an issue explaining the behavior. 

This PR also:
* Closes #223 (I even included this in a test).
* Closes #266.
* Fixes the weird behavior of the `HFac` variables when transforming the data mentioned in #136.

### CODE REVIEW

**Review by ThomasHaine — APPROVED** [review]
Looks great to me @Mikejmnez. Thanks for working so hard on this. Once the failing build is fixed, please merge and make a new OceanSpy release.

**Comment by Mikejmnez** [comment]
Well this is weird... All tests are passing.

**Comment by MaceKuailv** [comment]
Am I hallucinating? I saw the same fail as mine and the bots on this pull request last night.

**Comment by Mikejmnez** [comment]
I checked on the ***Files changed*** for this PR, and it states that I am supposedly changing ```.github/workflows/ci.yaml``` and ```.pre-commit-config.yaml``` but I am not, relative to ```hainegroup/oceanspy/```. You can take a look at the code on the main repository. What I did is I did change those relative to my own fork (```Mikejmnez/oceanspy```) since I started working on this fork before those changes happened and needed to keep on track of the changes...

So I don't understand why all tests are passing, but that is great news I guess!

**Comment by ThomasHaine** [comment]
Interesting. Could be a github bug?  Anyway, feel free to merge!

**Comment by malmans2** [comment]
Hi! I noticed this discussion glancing through.
Keep in mind that the github action that installs the environment is cached. I think the way it's set up right now, the cache is invalidated if the environment.yml changes or once a day. Each PR is cached separately. Not sure if it explains what's happening, but here is the link to the GH action in case you want to have a look and/or adjust the settings we have right now: https://github.com/mamba-org/provision-with-micromamba

**Pull request merged**
