### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by malmans2**
Added some tests:
* OceanDataset
* open_oceandataset

### CODE REVIEW

**Comment by malmans2** [comment]
I've added the get_started() function under open_oceandataset. 
It's very useful for testing as well because it takes less than 1s to open it, so you don't have to wait the annoying 20s of ERAI and ASR.

**Review by ThomasHaine — APPROVED** [review]
Looks good!

**Comment by malmans2** [comment]
Address #60

**Comment by malmans2** [comment]
* Added test for subsample
* Address #58 : @renskegelderloos  can you please close the issue if it's fixed?

There are a couple of minor syntax changes: 
1. `add_DataArray` and `merge_Dataset` have been replaced by `merge_into_oceandataset`
2. The subsample shortcuts are now organized as the module:
```python
# OLD:
od_cut = od.cutout(ZRange=0)
# NEW:
od_cut = od.subsample.cutout(ZRange=0)
```

**Comment by ThomasHaine** [comment]
I hit errors when I run pytest oceanspy on SciServer (after I git pull, then pip install):

================================================================= test session starts =================================================================
platform linux -- Python 3.6.7, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: /home/idies/workspace/Storage/Thomas.Haine/persistent/OceanSpy_dev/oceanspy, inifile: setup.cfg
collected 0 items / 4 errors

======================================================================= ERRORS ========================================================================
___________________________________________ ERROR collecting oceanspy/tests/test_oceandataset_attributes.py ___________________________________________
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:68: in _get_default_engine_netcdf
    import netCDF4  # noqa
E   ModuleNotFoundError: No module named 'netCDF4'

During handling of the above exception, another exception occurred:
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:72: in _get_default_engine_netcdf
    import scipy.io.netcdf  # noqa
E   ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:
oceanspy/tests/test_oceandataset_attributes.py:9: in <module>
    from . datasets import datasets
oceanspy/tests/datasets.py:155: in <module>
    'MITgcm_curv_nc' : Datasets().MITgcm_curv_nc()}
oceanspy/tests/datasets.py:115: in MITgcm_curv_nc
    ds  = xr.tutorial.open_dataset('rasm')
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/tutorial.py:85: in open_dataset
    ds = _open_dataset(localfile, **kws)
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:318: in open_dataset
    allow_remote=True)
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:88: in _get_default_engine
    engine = _get_default_engine_netcdf()
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:75: in _get_default_engine_netcdf
    raise ValueError('cannot read or write netCDF files without '
E   ValueError: cannot read or write netCDF files without netCDF4-python or scipy installed
____________________________________________ ERROR collecting oceanspy/tests/test_oceandataset_methods.py _____________________________________________
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:68: in _get_default_engine_netcdf
    import netCDF4  # noqa
E   ModuleNotFoundError: No module named 'netCDF4'

During handling of the above exception, another exception occurred:
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:72: in _get_default_engine_netcdf
    import scipy.io.netcdf  # noqa
E   ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:
oceanspy/tests/test_oceandataset_methods.py:3: in <module>
    from . datasets import (aliased_ods, oceandatasets)
oceanspy/tests/datasets.py:155: in <module>
    'MITgcm_curv_nc' : Datasets().MITgcm_curv_nc()}
oceanspy/tests/datasets.py:115: in MITgcm_curv_nc
    ds  = xr.tutorial.open_dataset('rasm')
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/tutorial.py:85: in open_dataset
    ds = _open_dataset(localfile, **kws)
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:318: in open_dataset
    allow_remote=True)
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:88: in _get_default_engine
    engine = _get_default_engine_netcdf()
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:75: in _get_default_engine_netcdf
    raise ValueError('cannot read or write netCDF files without '
E   ValueError: cannot read or write netCDF files without netCDF4-python or scipy installed
______________________________________________ ERROR collecting oceanspy/tests/test_open_oceandataset.py ______________________________________________
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:68: in _get_default_engine_netcdf
    import netCDF4  # noqa
E   ModuleNotFoundError: No module named 'netCDF4'

During handling of the above exception, another exception occurred:
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:72: in _get_default_engine_netcdf
    import scipy.io.netcdf  # noqa
E   ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:
oceanspy/tests/test_open_oceandataset.py:7: in <module>
    from . datasets import (datasets, oceandatasets)
oceanspy/tests/datasets.py:155: in <module>
    'MITgcm_curv_nc' : Datasets().MITgcm_curv_nc()}
oceanspy/tests/datasets.py:115: in MITgcm_curv_nc
    ds  = xr.tutorial.open_dataset('rasm')
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/tutorial.py:85: in open_dataset
    ds = _open_dataset(localfile, **kws)
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:318: in open_dataset
    allow_remote=True)
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:88: in _get_default_engine
    engine = _get_default_engine_netcdf()
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:75: in _get_default_engine_netcdf
    raise ValueError('cannot read or write netCDF files without '
E   ValueError: cannot read or write netCDF files without netCDF4-python or scipy installed
__________________________________________________ ERROR collecting oceanspy/tests/test_subsample.py __________________________________________________
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:68: in _get_default_engine_netcdf
    import netCDF4  # noqa
E   ModuleNotFoundError: No module named 'netCDF4'

During handling of the above exception, another exception occurred:
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:72: in _get_default_engine_netcdf
    import scipy.io.netcdf  # noqa
E   ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:
oceanspy/tests/test_subsample.py:6: in <module>
    from . datasets import (aliased_ods, oceandatasets)
oceanspy/tests/datasets.py:155: in <module>
    'MITgcm_curv_nc' : Datasets().MITgcm_curv_nc()}
oceanspy/tests/datasets.py:115: in MITgcm_curv_nc
    ds  = xr.tutorial.open_dataset('rasm')
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/tutorial.py:85: in open_dataset
    ds = _open_dataset(localfile, **kws)
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:318: in open_dataset
    allow_remote=True)
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:88: in _get_default_engine
    engine = _get_default_engine_netcdf()
/home/idies/miniconda3/envs/ospy_docs/lib/python3.6/site-packages/xarray/backends/api.py:75: in _get_default_engine_netcdf
    raise ValueError('cannot read or write netCDF files without '
E   ValueError: cannot read or write netCDF files without netCDF4-python or scipy installed
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================== 4 error in 2.13 seconds ===============================================================

**Comment by malmans2** [comment]
Not sure why. 
To double check I've created a new container and installed everything from scratch and it's working for me.
Here is what I've done:
Image: Python+R
```bash
$ conda config --remove channels defaults
$ conda config --add channels conda-forge
$ conda install -y dask distributed bottleneck netCDF4 xarray cartopy esmpy ffmpeg
$ pip install geopy xgcm xesmf xmitgcm
$ git clone --single-branch --branch add_tests https://github.com/malmans2/oceanspy.git
$ pip install -e oceanspy/
$ pytest oceanspy
```
I've cloned oceanspy in my `persistent` directory, and it looks like `pytest oceanspy` works from both `persistent` or `oceanspy/`.
Here is what shows up in my terminal:
```console
===================================================================== test session starts =====================================================================
platform linux -- Python 3.6.6, pytest-3.8.2, py-1.7.0, pluggy-0.8.0
rootdir: /home/idies/workspace/Storage/malmans2/persistent/oceanspy, inifile: setup.cfg
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 108 items

oceanspy/tests/test_oceandataset_attributes.py .........                                                                                                [  8%]
oceanspy/tests/test_oceandataset_methods.py ...........                                                                                                 [ 18%]
oceanspy/tests/test_open_oceandataset.py ....                                                                                                           [ 22%]
oceanspy/tests/test_subsample.py ........s.....s........s.....s..s..s.....s........s.....s..s..s.....s...............                                   [100%]

=========================================================== 96 passed, 12 skipped in 17.79 seconds ============================================================```

**Comment by ThomasHaine** [comment]
Thanks. Yes, it works for me too with a fresh container. Except I get this warning:

================================================================== warnings summary ===================================================================
/home/idies/workspace/Storage/Thomas.Haine/persistent/OceanSpy_dev/oceanspy/oceanspy/compute.py:204: DeprecationWarning: invalid escape sequence \l
  """

**Comment by malmans2** [comment]
With this push compute functions creating dynamic variables (e.g., gradient, divergence, ...) are completed. The last version of the documentation is in the shared folder on SciServer.
* Add tests (differences are tested using sinusoidal functions)
* Address this: https://github.com/malmans2/oceanspy/issues/54#issuecomment-469052364
* More robust weight average. There is now one compute function only (`compute.weighted_mean`) that will work for 1D, 2D, and 3D variables. Now you can compute the weighted mean of Eta, EXF, ... It's possible to output the weights as well, and the units should be correct: (m^3 for volume, m^2 for surfaces, ...). @ThomasHaine  you will need to adjust a little your scripts because of the new syntax, but hopefully it's an easy fix. Every variable has it's own weights because it's important to take care of NaN. E.g., if you want the average Temp>0 and you mask the Temp variable first. This new implementation will make very easy to use weighted means for plotting (as discussed during group meeting with @renskegelderloos ). 
* New syntax for shortcuts: E.g., `od.compute.gradient(...)`. It will automatically merge into the oceandataset. Default is `overwrite=False`. You'll get warnings if a variable that you're trying to merge is already in the oceandataset. If you want to overwrite: `od.compute.gradient(overwrite=True)`

Next: test compute functions creating static variables and make the syntax consistent.

**Comment by malmans2** [comment]
* Compute is fully tested and documented
* Added integral

**Comment by malmans2** [comment]
Tests now pass for both python 3.5 and 3.6. we might want to add 3.7. SciServer is currently using 3.6.

**Comment by malmans2** [comment]
* Add animation test. I they pass for python 3.5 we're ready to push to production and focus on tutorial/documentation

**Pull request merged**
